# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
before_install:
  - pip install pytest
install:
  - python setup.py install
script: py.test
